[[bars]]
name = "404"
osm-node-id = 6261579531

[[bars]]
name = "Au Fût et à mesure"
osm-node-id = 2389428129

[[bars]]
name = "Bar à l'Ouest"
osm-node-id = 1129614534

[[bars]]
name = "Barberousse"
osm-node-id = 1008928523

[[bars]]
name = "Bar Phenomen"
osm-node-id = 2379963204

[[bars]]
name = "Bar Sun Valley"
osm-node-id = 315986993

[[bars]]
name = "Beer O'Clock"
osm-way-id = 33139056

[[bars]]
name = "Brugs"
osm-node-id = 6363692914

[[bars]]
name = "D'Enfer Pub"
osm-node-id = 6583809375

[[bars]]
name = "Keep It Weird"
osm-node-id = 2435592232

[[bars]]
name = "Kiltin' Brewpub"
osm-node-id = 7800351426

[[bars]]
name = "La Natation"
osm-node-id = 961806837

[[bars]]
name = "Le Clos des Maronniers"
osm-node-id = 2667363750

[[bars]]
name = "Le Couche Tard"
osm-node-id = 2435592234

[[bars]]
name = "Le Jules Verne"
osm-node-id = 1116093384

[[bars]]
name = "Les BerThoM"
osm-node-id = 387000657

[[bars]]
name = "Les Copains d'Abord"
osm-node-id = 2269730505

[[bars]]
name = "Le Subway"
osm-node-id = 293850061

[[bars]]
name = "Le Tonneau de Diogène"
osm-node-id = 4020034171

[[bars]]
name = "Le Tord Boyaux"
osm-node-id = 1014442587

[[bars]]
name = "Le Vocalise"
osm-node-id = 2297205872

[[bars]]
name = "O'Callaghan"
osm-node-id = 1029745499

[[bars]]
name = "Paye Ta Bière"
osm-node-id = 5470994023

[[bars]]
name = "Pharaon Pub"
osm-way-id = 32666584

[[bars]]
name = "Pub des copains"
osm-node-id = 32631649

[[bars]]
name = "Sos Apero"
osm-node-id = 2577938497

[[bars]]
name = "Turnover"
osm-node-id = 5571941293

[[bars]]
name = "Une Petite Mousse"
osm-node-id = 6612121556

[[bars]]
name = "VnB"
osm-way-id = 149488817

[[bars]]
name = "Wallstreat"
osm-node-id = 2379963181

[[bars]]
name = "Wanted Saloon"
osm-node-id = 6898027886
